<!--
	Website generated by CMS v02
	URL: http://demo.phpbasic.com
	Email: w2ajax@gmail.com
-->
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<link rel="stylesheet" type="text/css" href="css/common.css" />
<link rel="icon" href="../favicon.gif" type="image/x-icon" />
<title>CMS - {web_client}</title>       
<script type="text/javascript">var token  = '{token}';</script>
<script type="text/javascript" src="../plugins/jquery-1.3.2.min.js"></script>
<script type="text/javascript">var plugins_dir = '../';var root_dir = '{root_dir}'; var lang = '{system.lang}';</script>
<script type="text/javascript" src="../plugins/tableorder/jquery.tableorder.js"></script>
<script type="text/javascript" src="js/common.js"></script>
<script type="text/javascript" src="js/module.configure.js"></script>
<!--BOX enable_editor-->
<script type="text/javascript" src="../plugins/tinymce/tiny_mce.js"></script>
<script type="text/javascript" src="js/editor.js"></script><!--BOX enable_editor-->
<script type="text/javascript" src="../plugins/divbox/divbox.js"></script>
<link rel="stylesheet" href="../plugins/divbox/css/frontend.css" type="text/css" media="screen" />
<script type="text/javascript">
var access_new = '{access.new}';
var access_edit = '{access.edit}';
var access_delete = '{access.delete}';
</script>
<script type="text/javascript" src="js/validate.js"></script>
<link rel="stylesheet" href="css/validate.css" type="text/css" media="screen" />
<script src="../plugins/dateinput/jquery-ui-1.8.16.custom.js"></script>
<script src="../plugins/dateinput/timepicker.js"></script>

<link rel="stylesheet" type="text/css" href="../plugins/dateinput/date-picker.css" />
<script type="text/javascript" src="js/preview.js"></script>
