<?php defined('_ROOT') or die('Not Allowed');
$merge_block = 6;
$_tpl = '﻿<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>

<!--start:master_header-->
<!--
	Website generated by CMS v02
	URL: http://demo.phpbasic.com
	Email: w2ajax@gmail.com
-->
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<link rel="stylesheet" type="text/css" href="template/css/common.css" />
<link rel="icon" href="../favicon.gif" type="image/x-icon" />
<title>CMS - '.(isset($this->_data["."][0]['web_client'])?$this->_data["."][0]['web_client']:'').'</title>       
<script type="text/javascript">var token  = \''.(isset($this->_data["."][0]['token'])?$this->_data["."][0]['token']:'').'\';</script>
<script type="text/javascript" src="../plugins/jquery-1.3.2.min.js"></script>
<script type="text/javascript">var plugins_dir = \'../\';var root_dir = \''.(isset($this->_data["."][0]['root_dir'])?$this->_data["."][0]['root_dir']:'').'\'; var lang = \''.(isset($this->merge['system']['lang'])?$this->merge['system']['lang']:'').'\';</script>
<script type="text/javascript" src="../plugins/tableorder/jquery.tableorder.js"></script>
<script type="text/javascript" src="template/js/common.js"></script>
<script type="text/javascript" src="template/js/module.configure.js"></script>
'; if(isset($this->box['enable_editor'])){ $_tpl.= '
<script type="text/javascript" src="../plugins/tinymce/tiny_mce.js"></script>
<script type="text/javascript" src="template/js/editor.js"></script>';}$_tpl .= '
<script type="text/javascript" src="../plugins/divbox/divbox.js"></script>
<link rel="stylesheet" href="../plugins/divbox/css/frontend.css" type="text/css" media="screen" />
<script type="text/javascript">
var access_new = \''.(isset($this->merge['access']['new'])?$this->merge['access']['new']:'').'\';
var access_edit = \''.(isset($this->merge['access']['edit'])?$this->merge['access']['edit']:'').'\';
var access_delete = \''.(isset($this->merge['access']['delete'])?$this->merge['access']['delete']:'').'\';
</script>
<script type="text/javascript" src="template/js/validate.js"></script>
<link rel="stylesheet" href="template/css/validate.css" type="text/css" media="screen" />
<script src="../plugins/dateinput/jquery-ui-1.8.16.custom.js"></script>
<script src="../plugins/dateinput/timepicker.js"></script>

<link rel="stylesheet" type="text/css" href="../plugins/dateinput/date-picker.css" />
<script type="text/javascript" src="template/js/preview.js"></script>

<!--end:master_header-->

<script type="text/javascript" src="template/skins/default/js/common.js"></script>
<link rel="stylesheet" type="text/css" href="template/skins/default/css/style.css" />
<!--[if IE]>
<style type="text/css">
tr.show{ display: block; }
</style>
<![endif]--> 

</head>
<body>

<div class="wrapper">
	<div class="container">
		<div class="hd">
			<p class="hd-r">
				Welcome <span class="hd-username">'.(isset($this->merge['login_user']['fullname'])?$this->merge['login_user']['fullname']:'').'</span>, 
				<a href="?mod=user&act=update" class="hd-profile">'.(isset($this->merge['lang']['update_profile'])?$this->merge['lang']['update_profile']:'').'</a> or 
				<a href="?mod=user&act=reset" class="hd-resetPass">'.(isset($this->merge['lang']['reset_password'])?$this->merge['lang']['reset_password']:'').'</a> <span class="hd-divider">|</span> 
				<a href="?mod=user&act=logout" class="hd-logout">'.(isset($this->merge['lang']['logout'])?$this->merge['lang']['logout']:'').'</a>
			</p>
			<a class="hd-logo" href="./">'.(isset($this->_data["."][0]['web_client'])?$this->_data["."][0]['web_client']:'').'</a>
		</div>
		
		<div class="ct">
			<div class="side">
				<!--<p class="menu-des">Menu</p>
				<p class="menu-desSub">
					Manage the site by this menu.<br />
					Click to collapse the menu.
				</p>-->
				';if(isset($this->_data['leftmenu.'])){for($i=0;$i< count($this->_data['leftmenu.']);$i++){$_tpl .= '
				<div class="menu '.(isset($this->_data["leftmenu."][$i]["cls_cms"])?$this->_data["leftmenu."][$i]["cls_cms"]:'').'">
					<h2 id="'.(isset($this->_data["leftmenu."][$i]["id"])?$this->_data["leftmenu."][$i]["id"]:'').'menu">'.(isset($this->_data["leftmenu."][$i]["name"])?$this->_data["leftmenu."][$i]["name"]:'').'</h2>
					'.(isset($this->_data["leftmenu."][$i]["links"])?$this->_data["leftmenu."][$i]["links"]:'').'
				</div>
				';}}$_tpl .= '
			</div>
			
			<div class="main">
				<div class="mainInner">
					<div class="breadcrumb">'.(isset($this->_data["."][0]['breadcrumb'])?$this->_data["."][0]['breadcrumb']:'').'</div>
					<div class="module_description">'.(isset($this->_data["."][0]['module_description'])?$this->_data["."][0]['module_description']:'').'</div>				
					
<!--start:body-->
<div class="top_callFunc">
'; if(isset($this->box['breadcrumb_cat'])){ $_tpl.= '
	<div class="hide breadcrumb_cat">'.(isset($this->_data["."][0]['xpath'])?$this->_data["."][0]['xpath']:'').'</div>';}$_tpl .= '
	<a href="'.(isset($this->_data["."][0]['http_referer'])?$this->_data["."][0]['http_referer']:'').'" class="btn btn_back r">&lt; '.(isset($this->merge['lang']['back'])?$this->merge['lang']['back']:'').'</a>
</div>
<div class="form"><form action="" method="post" enctype="multipart/form-data" name="fcontent" id="fcontent">
<input type="hidden" name="draft_id" value="'.(isset($this->_data["."][0]['draft_id'])?$this->_data["."][0]['draft_id']:'').'" />
	<input type="hidden" name="draft_id" value="'.(isset($this->_data["."][0]['draft_id'])?$this->_data["."][0]['draft_id']:'').'" />
	<input type="hidden" name="draft" value="'.(isset($this->_data["."][0]['draft'])?$this->_data["."][0]['draft']:'').'" />

'; if(isset($this->box['language_tab'])){ $_tpl.= '
<div class="language_tab">';if(isset($this->_data['language.'])){for($i=0;$i< count($this->_data['language.']);$i++){$_tpl .= '
<a href="#" onclick="showLangTab(\''.(isset($this->_data["language."][$i]["ln"])?$this->_data["language."][$i]["ln"]:'').'\',this);" '.(isset($this->_data["language."][$i]["tab_default"])?$this->_data["language."][$i]["tab_default"]:'').'>'.(isset($this->_data["language."][$i]["ln_name"])?$this->_data["language."][$i]["ln_name"]:'').'</a> ';}}$_tpl .= '</div>
';}$_tpl .= '
<div class="error">'.(isset($this->_data["."][0]['msg'])?$this->_data["."][0]['msg']:'').'</div>
  <table width="100%" border="0" cellspacing="0" cellpadding="1" class="table-Form1">
  ';if(isset($this->_data['language.'])){for($i=0;$i< count($this->_data['language.']);$i++){$_tpl .= '
<tbody class="'.(isset($this->_data["language."][$i]["default_ln"])?$this->_data["language."][$i]["default_ln"]:'').' tab_language" id="tab_'.(isset($this->_data["language."][$i]["ln"])?$this->_data["language."][$i]["ln"]:'').'">
    <tr>
		<td class="td1">&nbsp;</td>
		<td class="td2">&nbsp;</td>
	</tr>
	'.(isset($this->_data["language."][$i]["ln_fields"])?$this->_data["language."][$i]["ln_fields"]:'').'
    <tr class="hide '.(isset($this->_data["."][0]['display_ln_icon'])?$this->_data["."][0]['display_ln_icon']:'').'">
      <td width="16%">Icon '.(isset($this->_data["language."][$i]["ln_alias"])?$this->_data["language."][$i]["ln_alias"]:'').' </td>
      <td width="84%"><input name="ln_icon['.(isset($this->_data["language."][$i]["ln"])?$this->_data["language."][$i]["ln"]:'').']" type="file" id="ln_icon['.(isset($this->_data["language."][$i]["ln"])?$this->_data["language."][$i]["ln"]:'').']" class="no_width">        '.(isset($this->_data["."][0]['size_ln_icon'])?$this->_data["."][0]['size_ln_icon']:'').'<br />
		<span class="hide"><a href="'.(isset($this->_data["."][0]['_UPLOAD'])?$this->_data["."][0]['_UPLOAD']:'').''.(isset($this->_data["language."][$i]["ln_icon"])?$this->_data["language."][$i]["ln_icon"]:'').'" class="mb">'.(isset($this->_data["language."][$i]["ln_icon"])?$this->_data["language."][$i]["ln_icon"]:'').'</a> 
	    <input type="checkbox" name="delete_ln_icon['.(isset($this->_data["language."][$i]["ln"])?$this->_data["language."][$i]["ln"]:'').']" class="no_width" value="1" /> 
		<input name="current_ln_icon['.(isset($this->_data["language."][$i]["ln"])?$this->_data["language."][$i]["ln"]:'').']" type="hidden" title="'.(isset($this->_data["language."][$i]["ln_icon"])?$this->_data["language."][$i]["ln_icon"]:'').'" value="'.(isset($this->_data["language."][$i]["ln_icon"])?$this->_data["language."][$i]["ln_icon"]:'').'" class="box_delete_file" />
	    '.(isset($this->merge['lang']['delete'])?$this->merge['lang']['delete']:'').'		</span></td>
    </tr>
    <tr class="hide '.(isset($this->_data["."][0]['display_ln_image'])?$this->_data["."][0]['display_ln_image']:'').'">
      <td width="16%">Image '.(isset($this->_data["language."][$i]["ln_alias"])?$this->_data["language."][$i]["ln_alias"]:'').'</td>
      <td width="84%"><input name="ln_image['.(isset($this->_data["language."][$i]["ln"])?$this->_data["language."][$i]["ln"]:'').']" type="file" id="ln_image['.(isset($this->_data["language."][$i]["ln"])?$this->_data["language."][$i]["ln"]:'').']" class="no_width">
       
        '.(isset($this->_data["."][0]['size_ln_image'])?$this->_data["."][0]['size_ln_image']:'').'<br />
		<span class="hide"><a href="'.(isset($this->_data["."][0]['_UPLOAD'])?$this->_data["."][0]['_UPLOAD']:'').''.(isset($this->_data["language."][$i]["ln_image"])?$this->_data["language."][$i]["ln_image"]:'').'" class="mb">'.(isset($this->_data["language."][$i]["ln_image"])?$this->_data["language."][$i]["ln_image"]:'').'</a> 
		<input name="current_ln_image['.(isset($this->_data["language."][$i]["ln"])?$this->_data["language."][$i]["ln"]:'').']" type="hidden" title="'.(isset($this->_data["language."][$i]["ln_image"])?$this->_data["language."][$i]["ln_image"]:'').'" value="'.(isset($this->_data["language."][$i]["ln_image"])?$this->_data["language."][$i]["ln_image"]:'').'"  class="box_delete_file" />
	    <input type="checkbox" name="delete_ln_image['.(isset($this->_data["language."][$i]["ln"])?$this->_data["language."][$i]["ln"]:'').']" class="no_width" value="1" /> 
	    '.(isset($this->merge['lang']['delete'])?$this->merge['lang']['delete']:'').'		</span></td>
    </tr>
   <tr class="sep">
      <td></td>
      <td></td>
    </tr>
	</tbody>
';}}$_tpl .= '
  </table>
  <hr />
  <table width="100%" border="0" cellspacing="0" cellpadding="0"class="table-Form1">
	<tr>
		<td class="td1">&nbsp;</td>
		<td class="td2">&nbsp;</td>
	</tr>
';if(isset($this->_data['options.'])){for($i=0;$i< count($this->_data['options.']);$i++){$_tpl .= '

    <tr>
      <td  valign="top" class="textLabel">'.(isset($this->_data["options."][$i]["name"])?$this->_data["options."][$i]["name"]:'').'</td>
      <td>'.(isset($this->_data["options."][$i]["values"])?$this->_data["options."][$i]["values"]:'').'
        <a href="#" onclick="return addOptions('.(isset($this->_data["options."][$i]["typeid"])?$this->_data["options."][$i]["typeid"]:'').',\''.(isset($this->_data["options."][$i]["js_string"])?$this->_data["options."][$i]["js_string"]:'').'\',this);">New</a></td>
    </tr>
';}}$_tpl .= '
  </table>
  <table width="100%" border="0" cellspacing="0" cellpadding="1" class="table-Form1 '.(isset($this->_data["."][0]['hide_no_languages'])?$this->_data["."][0]['hide_no_languages']:'').'">
    <tr>
		<td class="td1">&nbsp;</td>
		<td class="td2">&nbsp;</td>
	</tr>
	'.(isset($this->_data["."][0]['main_catfields'])?$this->_data["."][0]['main_catfields']:'').'
    <tr class="hide '.(isset($this->_data["."][0]['display_icon'])?$this->_data["."][0]['display_icon']:'').'">
      <td>'.(isset($this->merge['lang']['icon'])?$this->merge['lang']['icon']:'').'</td>
      <td><input name="icon" type="file" id="icon" class="no_width">
        
        '.(isset($this->_data["."][0]['size_icon'])?$this->_data["."][0]['size_icon']:'').'
		<br />
		<span class="hide"><a href="'.(isset($this->_data["."][0]['_UPLOAD'])?$this->_data["."][0]['_UPLOAD']:'').''.(isset($this->_data["."][0]['icon'])?$this->_data["."][0]['icon']:'').'" class="mb">'.(isset($this->_data["."][0]['icon'])?$this->_data["."][0]['icon']:'').'</a> 
		<input name="current_icon" type="hidden" title="'.(isset($this->_data["."][0]['icon'])?$this->_data["."][0]['icon']:'').'" value="'.(isset($this->_data["."][0]['icon'])?$this->_data["."][0]['icon']:'').'" class="box_delete_file" />
	    <input type="checkbox" name="delete_icon" class="no_width" value="1" /> 
	    '.(isset($this->merge['lang']['delete'])?$this->merge['lang']['delete']:'').'		
		</span></td>
    </tr>
    <tr class="hide '.(isset($this->_data["."][0]['display_image'])?$this->_data["."][0]['display_image']:'').'">
      <td>'.(isset($this->merge['lang']['image'])?$this->merge['lang']['image']:'').'</td>
      <td><input name="image" type="file" id="image" class="no_width">
        '.(isset($this->_data["."][0]['size_image'])?$this->_data["."][0]['size_image']:'').'
		<br /><span class="hide"><a href="'.(isset($this->_data["."][0]['_UPLOAD'])?$this->_data["."][0]['_UPLOAD']:'').''.(isset($this->_data["."][0]['image'])?$this->_data["."][0]['image']:'').'" class="mb">'.(isset($this->_data["."][0]['image'])?$this->_data["."][0]['image']:'').'</a> 
		  <input type="checkbox" name="delete_image" class="no_width" value="1" /> 
		  <input name="current_image" type="hidden" title="'.(isset($this->_data["."][0]['image'])?$this->_data["."][0]['image']:'').'" value="'.(isset($this->_data["."][0]['image'])?$this->_data["."][0]['image']:'').'" class="box_delete_file" />
		  '.(isset($this->merge['lang']['delete'])?$this->merge['lang']['delete']:'').' </span></td>
    </tr>
	
	';if(isset($this->_data['file_extra.'])){for($i=0;$i< count($this->_data['file_extra.']);$i++){$_tpl .= '
	<tr>
		<td class="textLabel"><label>'.(isset($this->_data["file_extra."][$i]["name"])?$this->_data["file_extra."][$i]["name"]:'').'</label></td>
		<td><input name="file_extra'.(isset($this->_data["file_extra."][$i]["stt"])?$this->_data["file_extra."][$i]["stt"]:'').'" type="file" id="image" class="no_width">
			<input name="file_extra_type['.(isset($this->_data["file_extra."][$i]["stt"])?$this->_data["file_extra."][$i]["stt"]:'').']" type="hidden" value="'.(isset($this->_data["file_extra."][$i]["type"])?$this->_data["file_extra."][$i]["type"]:'').'" />
			<input name="file_extra_code['.(isset($this->_data["file_extra."][$i]["stt"])?$this->_data["file_extra."][$i]["stt"]:'').']" type="hidden" value="'.(isset($this->_data["file_extra."][$i]["code"])?$this->_data["file_extra."][$i]["code"]:'').'" />
			'.(isset($this->_data["file_extra."][$i]["note"])?$this->_data["file_extra."][$i]["note"]:'').'  
			<p class="hide">
			<input name="current_file_extra'.(isset($this->_data["file_extra."][$i]["stt"])?$this->_data["file_extra."][$i]["stt"]:'').'" type="hidden" title="'.(isset($this->_data["file_extra."][$i]["file"])?$this->_data["file_extra."][$i]["file"]:'').'" value="'.(isset($this->_data["file_extra."][$i]["file"])?$this->_data["file_extra."][$i]["file"]:'').'" class="box_delete_file" />
			<a href="'.(isset($this->_data["."][0]['_UPLOAD'])?$this->_data["."][0]['_UPLOAD']:'').''.(isset($this->_data["file_extra."][$i]["file"])?$this->_data["file_extra."][$i]["file"]:'').'" class="mb">'.(isset($this->_data["file_extra."][$i]["file"])?$this->_data["file_extra."][$i]["file"]:'').'</a>
				<input type="checkbox" name="delete_file_extra'.(isset($this->_data["file_extra."][$i]["stt"])?$this->_data["file_extra."][$i]["stt"]:'').'" class="no_width" value="1" />
				'.(isset($this->merge['lang']['delete'])?$this->merge['lang']['delete']:'').'			</p>				</td>
	</tr>';}}$_tpl .= '
    <tr class="hide '.(isset($this->_data["."][0]['display_enable_catdate'])?$this->_data["."][0]['display_enable_catdate']:'').'">
      <td>'.(isset($this->merge['lang']['date'])?$this->merge['lang']['date']:'').'</td>
      <td>
      <input type="text" name="date" value="'.(isset($this->_data["."][0]['date'])?$this->_data["."][0]['date']:'').'" class="'.(isset($this->_data["."][0]['enable_catdate_type'])?$this->_data["."][0]['enable_catdate_type']:'').'picker" />
      </td>
    </tr>
  </table>
  <div class="table_list '.(isset($this->_data["."][0]['hide_no_languages'])?$this->_data["."][0]['hide_no_languages']:'').'" align="right">
	<input type="submit" class="btn" name="Submit" value="Save">
	'; if(isset($this->box['btn_preview'])){ $_tpl.= '<input type="submit" class="btn btn_preview" name="btn_preview"  value="'.(isset($this->merge['lang']['btn_preview'])?$this->merge['lang']['btn_preview']:'').'">';}$_tpl .= '
	<input type="button" class="btn btn_cancel" name="" value="Cancel" onclick="location.href=\''.(isset($this->_data["."][0]['http_referer'])?$this->_data["."][0]['http_referer']:'').'\';">
  </div>
</form></div>
<script type="text/javascript">
	var opt = {
		required: ['.(isset($this->_data["."][0]['required_catfields'])?$this->_data["."][0]['required_catfields']:'').'],
		required_lang: ['.(isset($this->_data["."][0]['required_ln_catfields'])?$this->_data["."][0]['required_ln_catfields']:'').'],
		lang: \''.(isset($this->_data["."][0]['language'])?$this->_data["."][0]['language']:'').'\'
	};
	if('.(isset($this->_data["."][0]['access_action'])?$this->_data["."][0]['access_action']:'').' == \'\') opt[\'disabled\'] = \''.(isset($this->merge['lang']['user_no_access'])?$this->merge['lang']['user_no_access']:'').'\';
	$(\'form#fcontent\').preview();
	$(\'form#fcontent\').validate(opt);

</script>

<!--end:body-->

				</div>			
			</div>
		</div>
		
		<div class="ft">
			&copy; Copyright '.(isset($this->_data["."][0]['system_year'])?$this->_data["."][0]['system_year']:'').' '.(isset($this->_data["."][0]['web_client'])?$this->_data["."][0]['web_client']:'').'.
		</div>
	</div>
</div>

<table width="5" height="100%" cellpadding="0" cellspacing="0" border="0" class="btn_expandMenu"><tr><td>&nbsp;</td></tr></table>


<!--start:master_footer-->
<div class="cms_overlay"></div>
<noscript>
	<style type="text/css">
		.wrapper{ display: none; }
	</style>
	<div class="noscript">JavaScript must be enabled in order for you to use '.(isset($this->_data["."][0]['web_client'])?$this->_data["."][0]['web_client']:'').' CMS. Please enable JavaScript by changing your browser options, then press <strong>F5</strong> to load page</div>
</noscript>

<!--end:master_footer-->


</body>
</html>'; ?>