<?php defined('_ROOT') or die('Not Allowed');
$merge_block = 6;
$_tpl = '﻿<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>

<!--start:master_header-->
<!--
	Website generated by CMS v02
	URL: http://demo.phpbasic.com
	Email: w2ajax@gmail.com
-->
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<link rel="stylesheet" type="text/css" href="template/css/common.css" />
<link rel="icon" href="../favicon.gif" type="image/x-icon" />
<title>CMS - '.(isset($this->_data["."][0]['web_client'])?$this->_data["."][0]['web_client']:'').'</title>       
<script type="text/javascript">var token  = \''.(isset($this->_data["."][0]['token'])?$this->_data["."][0]['token']:'').'\';</script>
<script type="text/javascript" src="../plugins/jquery-1.3.2.min.js"></script>
<script type="text/javascript">var plugins_dir = \'../\';var root_dir = \''.(isset($this->_data["."][0]['root_dir'])?$this->_data["."][0]['root_dir']:'').'\'; var lang = \''.(isset($this->merge['system']['lang'])?$this->merge['system']['lang']:'').'\';</script>
<script type="text/javascript" src="../plugins/tableorder/jquery.tableorder.js"></script>
<script type="text/javascript" src="template/js/common.js"></script>
<script type="text/javascript" src="template/js/module.configure.js"></script>
'; if(isset($this->box['enable_editor'])){ $_tpl.= '
<script type="text/javascript" src="../plugins/tinymce/tiny_mce.js"></script>
<script type="text/javascript" src="template/js/editor.js"></script>';}$_tpl .= '
<script type="text/javascript" src="../plugins/divbox/divbox.js"></script>
<link rel="stylesheet" href="../plugins/divbox/css/frontend.css" type="text/css" media="screen" />
<script type="text/javascript">
var access_new = \''.(isset($this->merge['access']['new'])?$this->merge['access']['new']:'').'\';
var access_edit = \''.(isset($this->merge['access']['edit'])?$this->merge['access']['edit']:'').'\';
var access_delete = \''.(isset($this->merge['access']['delete'])?$this->merge['access']['delete']:'').'\';
</script>
<script type="text/javascript" src="template/js/validate.js"></script>
<link rel="stylesheet" href="template/css/validate.css" type="text/css" media="screen" />
<script src="../plugins/dateinput/jquery-ui-1.8.16.custom.js"></script>
<script src="../plugins/dateinput/timepicker.js"></script>

<link rel="stylesheet" type="text/css" href="../plugins/dateinput/date-picker.css" />
<script type="text/javascript" src="template/js/preview.js"></script>

<!--end:master_header-->

<script type="text/javascript" src="template/skins/default/js/common.js"></script>
<link rel="stylesheet" type="text/css" href="template/skins/default/css/style.css" />
<!--[if IE]>
<style type="text/css">
tr.show{ display: block; }
</style>
<![endif]--> 

</head>
<body>

<div class="wrapper">
	<div class="container">
		<div class="hd">
			<p class="hd-r">
				Welcome <span class="hd-username">'.(isset($this->merge['login_user']['fullname'])?$this->merge['login_user']['fullname']:'').'</span>, 
				<a href="?mod=user&act=update" class="hd-profile">'.(isset($this->merge['lang']['update_profile'])?$this->merge['lang']['update_profile']:'').'</a> or 
				<a href="?mod=user&act=reset" class="hd-resetPass">'.(isset($this->merge['lang']['reset_password'])?$this->merge['lang']['reset_password']:'').'</a> <span class="hd-divider">|</span> 
				<a href="?mod=user&act=logout" class="hd-logout">'.(isset($this->merge['lang']['logout'])?$this->merge['lang']['logout']:'').'</a>
			</p>
			<a class="hd-logo" href="./">'.(isset($this->_data["."][0]['web_client'])?$this->_data["."][0]['web_client']:'').'</a>
		</div>
		
		<div class="ct">
			<div class="side">
				<!--<p class="menu-des">Menu</p>
				<p class="menu-desSub">
					Manage the site by this menu.<br />
					Click to collapse the menu.
				</p>-->
				';if(isset($this->_data['leftmenu.'])){for($i=0;$i< count($this->_data['leftmenu.']);$i++){$_tpl .= '
				<div class="menu '.(isset($this->_data["leftmenu."][$i]["cls_cms"])?$this->_data["leftmenu."][$i]["cls_cms"]:'').'">
					<h2 id="'.(isset($this->_data["leftmenu."][$i]["id"])?$this->_data["leftmenu."][$i]["id"]:'').'menu">'.(isset($this->_data["leftmenu."][$i]["name"])?$this->_data["leftmenu."][$i]["name"]:'').'</h2>
					'.(isset($this->_data["leftmenu."][$i]["links"])?$this->_data["leftmenu."][$i]["links"]:'').'
				</div>
				';}}$_tpl .= '
			</div>
			
			<div class="main">
				<div class="mainInner">
					<div class="breadcrumb">'.(isset($this->_data["."][0]['breadcrumb'])?$this->_data["."][0]['breadcrumb']:'').'</div>
					<div class="module_description">'.(isset($this->_data["."][0]['module_description'])?$this->_data["."][0]['module_description']:'').'</div>				
					
<!--start:body-->
<div class="top_callFunc">
	<a href="'.(isset($this->_data["."][0]['http_referer'])?$this->_data["."][0]['http_referer']:'').'" class="btn r">&lt; '.(isset($this->merge['lang']['back'])?$this->merge['lang']['back']:'').'</a>
</div>
<div class="form"><form action="" method="post" id="fcontent" enctype="multipart/form-data" name="fcontent">

'; if(isset($this->box['language_tab'])){ $_tpl.= '
	<div class="language_tab">
	';if(isset($this->_data['language.'])){for($i=0;$i< count($this->_data['language.']);$i++){$_tpl .= '
		<a href="#" onclick="showLangTab(\''.(isset($this->_data["language."][$i]["ln"])?$this->_data["language."][$i]["ln"]:'').'\',this);" '.(isset($this->_data["language."][$i]["tab_default"])?$this->_data["language."][$i]["tab_default"]:'').'>'.(isset($this->_data["language."][$i]["ln_name"])?$this->_data["language."][$i]["ln_name"]:'').'</a>
	';}}$_tpl .= '
	</div>
';}$_tpl .= '

<div class="error">'.(isset($this->_data["."][0]['msg'])?$this->_data["."][0]['msg']:'').'</div>
  
<table width="100%" border="0" cellspacing="0" cellpadding="1" class="table-Form1">
';if(isset($this->_data['language.'])){for($i=0;$i< count($this->_data['language.']);$i++){$_tpl .= '
<tbody class="'.(isset($this->_data["language."][$i]["default_ln"])?$this->_data["language."][$i]["default_ln"]:'').' tab_language" id="tab_'.(isset($this->_data["language."][$i]["ln"])?$this->_data["language."][$i]["ln"]:'').'">
    <tr>
      <td class="textLabel">Name</td>
      <td><input type="text" name="name['.(isset($this->_data["language."][$i]["ln"])?$this->_data["language."][$i]["ln"]:'').']" value="'.(isset($this->_data["language."][$i]["name"])?$this->_data["language."][$i]["name"]:'').'" title="Vui long nhap Name" ></td>
    </tr>
    <tr>
      <td class="textLabel">Module name(url) <span class="description">'.(isset($this->_data["language."][$i]["ln_alias"])?$this->_data["language."][$i]["ln_alias"]:'').'</span></td>
      <td><input name="module_name['.(isset($this->_data["language."][$i]["ln"])?$this->_data["language."][$i]["ln"]:'').']" type="text" id="module_name['.(isset($this->_data["language."][$i]["ln"])?$this->_data["language."][$i]["ln"]:'').']" title="Vui long nhap Name" value="'.(isset($this->_data["language."][$i]["module_name"])?$this->_data["language."][$i]["module_name"]:'').'" ></td>
    </tr>
    <tr>
      <td class="textLabel">Meta title '.(isset($this->_data["language."][$i]["ln_alias"])?$this->_data["language."][$i]["ln_alias"]:'').'</td>
      <td><input name="web_title['.(isset($this->_data["language."][$i]["ln"])?$this->_data["language."][$i]["ln"]:'').']" type="text" id="web_title['.(isset($this->_data["language."][$i]["ln"])?$this->_data["language."][$i]["ln"]:'').']" title="Vui long nhap Name" value="'.(isset($this->_data["language."][$i]["web_title"])?$this->_data["language."][$i]["web_title"]:'').'" ></td>
    </tr>
    <tr>
      <td class="textLabel">Meta keywords  '.(isset($this->_data["language."][$i]["ln_alias"])?$this->_data["language."][$i]["ln_alias"]:'').'</td>
      <td><textarea name="web_keyword['.(isset($this->_data["language."][$i]["ln"])?$this->_data["language."][$i]["ln"]:'').']" rows="5" id="web_keyword['.(isset($this->_data["language."][$i]["ln"])?$this->_data["language."][$i]["ln"]:'').']" title="Vui long nhap Intro">'.(isset($this->_data["language."][$i]["web_keyword"])?$this->_data["language."][$i]["web_keyword"]:'').'</textarea></td>
    </tr>
    <tr>
      <td class="textLabel">Meta description  '.(isset($this->_data["language."][$i]["ln_alias"])?$this->_data["language."][$i]["ln_alias"]:'').' </td>
      <td><textarea name="web_desc['.(isset($this->_data["language."][$i]["ln"])?$this->_data["language."][$i]["ln"]:'').']" rows="5" id="web_desc['.(isset($this->_data["language."][$i]["ln"])?$this->_data["language."][$i]["ln"]:'').']">'.(isset($this->_data["language."][$i]["web_desc"])?$this->_data["language."][$i]["web_desc"]:'').'</textarea></td>
    </tr>
    <tr>
      <td class="textLabel">Meta extra '.(isset($this->_data["language."][$i]["ln_alias"])?$this->_data["language."][$i]["ln_alias"]:'').' </td>
      <td><textarea name="meta_extra['.(isset($this->_data["language."][$i]["ln"])?$this->_data["language."][$i]["ln"]:'').']" rows="5" id="meta_extra['.(isset($this->_data["language."][$i]["ln"])?$this->_data["language."][$i]["ln"]:'').']">'.(isset($this->_data["language."][$i]["meta_extra"])?$this->_data["language."][$i]["meta_extra"]:'').'</textarea></td>
    </tr>
	</tbody>
';}}$_tpl .= '
  </table>

<hr />

<table width="100%" border="0" cellspacing="0" cellpadding="0" class="table-Form1 '.(isset($this->_data["."][0]['hide_no_language'])?$this->_data["."][0]['hide_no_language']:'').'">
    <tr>
      <td class="textLabel">Module Folder </td>
      <td><input name="module" type="text" id="module" value="'.(isset($this->_data["."][0]['module'])?$this->_data["."][0]['module']:'').'" /></td>
    </tr>
	
	<tr>
      <td class="textLabel">&nbsp;</td>
    	<td align="right">
			<input type="submit" class="btn" name="Submit" value="'.(isset($this->merge['lang']['save'])?$this->merge['lang']['save']:'').'">
			<input type="button" class="btn btn_cancel" name="" value="'.(isset($this->merge['lang']['cancel'])?$this->merge['lang']['cancel']:'').'" onClick="location.href=\''.(isset($this->_data["."][0]['http_referer'])?$this->_data["."][0]['http_referer']:'').'\';">		</td>
    </tr>
  </table>

  <!--<div class="table-Form1 '.(isset($this->_data["."][0]['hide_no_language'])?$this->_data["."][0]['hide_no_language']:'').'">
    <table width="100%" border="0" cellspacing="0" cellpadding="0">
      <tr>
        <td width="79%"><table width="100%" border="0" cellspacing="0" cellpadding="0">
          <tr class="hide" '.(isset($this->_data["."][0]['display_gallery'])?$this->_data["."][0]['display_gallery']:'').'>
            <td align="right"><span class="hide"  '.(isset($this->_data["."][0]['display_update'])?$this->_data["."][0]['display_update']:'').'><select name="back" id="back">
        <option value="1" '.(isset($this->_data["."][0]['back_list_1'])?$this->_data["."][0]['back_list_1']:'').'>Go back to list</option>
        <option value="0" '.(isset($this->_data["."][0]['back_list_0'])?$this->_data["."][0]['back_list_0']:'').'>Keep me here</option>
        </select></span></td>
          </tr>
        </table></td>
        <td width="21%" align="right"><input type="submit" class="btn" name="Submit" value="&nbsp;"> <input type="button" class="btn_cancel" name="" value="&nbsp;" onClick="location.href=\''.(isset($this->_data["."][0]['http_referer'])?$this->_data["."][0]['http_referer']:'').'\';"></td>
      </tr>
    </table>
    
  </div>-->
  
</form></div>
<script type="text/javascript">
	var opt = {
		required: [\'module\'],
		lang: \''.(isset($this->_data["."][0]['language'])?$this->_data["."][0]['language']:'').'\'
	};
	$(\'form#fcontent\').validate(opt);

</script>
<!--end:body-->

				</div>			
			</div>
		</div>
		
		<div class="ft">
			&copy; Copyright '.(isset($this->_data["."][0]['system_year'])?$this->_data["."][0]['system_year']:'').' '.(isset($this->_data["."][0]['web_client'])?$this->_data["."][0]['web_client']:'').'.
		</div>
	</div>
</div>

<table width="5" height="100%" cellpadding="0" cellspacing="0" border="0" class="btn_expandMenu"><tr><td>&nbsp;</td></tr></table>


<!--start:master_footer-->
<div class="cms_overlay"></div>
<noscript>
	<style type="text/css">
		.wrapper{ display: none; }
	</style>
	<div class="noscript">JavaScript must be enabled in order for you to use '.(isset($this->_data["."][0]['web_client'])?$this->_data["."][0]['web_client']:'').' CMS. Please enable JavaScript by changing your browser options, then press <strong>F5</strong> to load page</div>
</noscript>

<!--end:master_footer-->


</body>
</html>'; ?>