<?php defined('_ROOT') or die('Not Allowed');
$merge_block = 8;
$_tpl = '﻿<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>

<!--start:master_header-->
<!--
	Website generated by CMS v02
	URL: http://demo.phpbasic.com
	Email: w2ajax@gmail.com
-->
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<link rel="stylesheet" type="text/css" href="template/css/common.css" />
<link rel="icon" href="../favicon.gif" type="image/x-icon" />
<title>CMS - '.(isset($this->_data["."][0]['web_client'])?$this->_data["."][0]['web_client']:'').'</title>       
<script type="text/javascript">var token  = \''.(isset($this->_data["."][0]['token'])?$this->_data["."][0]['token']:'').'\';</script>
<script type="text/javascript" src="../plugins/jquery-1.3.2.min.js"></script>
<script type="text/javascript">var plugins_dir = \'../\';var root_dir = \''.(isset($this->_data["."][0]['root_dir'])?$this->_data["."][0]['root_dir']:'').'\'; var lang = \''.(isset($this->merge['system']['lang'])?$this->merge['system']['lang']:'').'\';</script>
<script type="text/javascript" src="../plugins/tableorder/jquery.tableorder.js"></script>
<script type="text/javascript" src="template/js/common.js"></script>
<script type="text/javascript" src="template/js/module.configure.js"></script>
'; if(isset($this->box['enable_editor'])){ $_tpl.= '
<script type="text/javascript" src="../plugins/tinymce/tiny_mce.js"></script>
<script type="text/javascript" src="template/js/editor.js"></script>';}$_tpl .= '
<script type="text/javascript" src="../plugins/divbox/divbox.js"></script>
<link rel="stylesheet" href="../plugins/divbox/css/frontend.css" type="text/css" media="screen" />
<script type="text/javascript">
var access_new = \''.(isset($this->merge['access']['new'])?$this->merge['access']['new']:'').'\';
var access_edit = \''.(isset($this->merge['access']['edit'])?$this->merge['access']['edit']:'').'\';
var access_delete = \''.(isset($this->merge['access']['delete'])?$this->merge['access']['delete']:'').'\';
</script>
<script type="text/javascript" src="template/js/validate.js"></script>
<link rel="stylesheet" href="template/css/validate.css" type="text/css" media="screen" />
<script type="text/javascript" src="../plugins/dateinput/dateinput.js"></script>

<!--end:master_header-->

<script type="text/javascript" src="template/skins/default/js/common.js"></script>
<link rel="stylesheet" type="text/css" href="template/skins/default/css/style.css" />
<!--[if IE]>
<style type="text/css">
tr.show{ display: block; }
</style>
<![endif]--> 

</head>
<body>

<div class="wrapper">
	<div class="container">
		<div class="hd">
			<p class="hd-r">
				Welcome <span class="hd-username">'.(isset($this->merge['login_user']['fullname'])?$this->merge['login_user']['fullname']:'').'</span>, 
				<a href="?mod=user&act=update" class="hd-profile">'.(isset($this->merge['lang']['update_profile'])?$this->merge['lang']['update_profile']:'').'</a> or 
				<a href="?mod=user&act=reset" class="hd-resetPass">'.(isset($this->merge['lang']['reset_password'])?$this->merge['lang']['reset_password']:'').'</a> <span class="hd-divider">|</span> 
				<a href="?mod=user&act=logout" class="hd-logout">'.(isset($this->merge['lang']['logout'])?$this->merge['lang']['logout']:'').'</a>
			</p>
			<a class="hd-logo" href="./">'.(isset($this->_data["."][0]['web_client'])?$this->_data["."][0]['web_client']:'').'</a>
		</div>
		
		<div class="ct">
			<div class="side">
				<!--<p class="menu-des">Menu</p>
				<p class="menu-desSub">
					Manage the site by this menu.<br />
					Click to collapse the menu.
				</p>-->
				';if(isset($this->_data['leftmenu.'])){for($i=0;$i< count($this->_data['leftmenu.']);$i++){$_tpl .= '
				<div class="menu '.(isset($this->_data["leftmenu."][$i]["cls_cms"])?$this->_data["leftmenu."][$i]["cls_cms"]:'').'">
					<h2 id="'.(isset($this->_data["leftmenu."][$i]["id"])?$this->_data["leftmenu."][$i]["id"]:'').'menu">'.(isset($this->_data["leftmenu."][$i]["name"])?$this->_data["leftmenu."][$i]["name"]:'').'</h2>
					'.(isset($this->_data["leftmenu."][$i]["links"])?$this->_data["leftmenu."][$i]["links"]:'').'
				</div>
				';}}$_tpl .= '
			</div>
			
			<div class="main">
				<div class="mainInner">
					<div class="breadcrumb">'.(isset($this->_data["."][0]['breadcrumb'])?$this->_data["."][0]['breadcrumb']:'').'</div>
					<div class="module_description">'.(isset($this->_data["."][0]['module_description'])?$this->_data["."][0]['module_description']:'').'</div>				
					
<!--start:body-->
<div class="top_callFunc">
'; if(isset($this->box['search_function'])){ $_tpl.= '
	<div class="searchForm table-Form1">
		<form id="form1" name="form1" method="get" action="">
			<input name="mod" type="hidden" id="mod" value="'.(isset($this->_data["."][0]['module'])?$this->_data["."][0]['module']:'').'" />
			<input name="type" type="hidden" id="type" value="'.(isset($this->_data["."][0]['type'])?$this->_data["."][0]['type']:'').'" />
			<input name="parentid" type="hidden" id="parentid" value="'.(isset($this->_data["."][0]['parentid'])?$this->_data["."][0]['parentid']:'').'" />
			<input name="q" type="text" class="txf-normal" id="q" value="'.(isset($this->_data["."][0]['q'])?$this->_data["."][0]['q']:'').'" onfocus="if(this.value==this.defaultValue) this.value=\'\';" onblur="if(this.value==\'\') this.value = this.defaultValue;" />
			<input name="cmd" type="submit" class="btn" id="cmd" value="'.(isset($this->merge['lang']['search'])?$this->merge['lang']['search']:'').'" />
			'.(isset($this->_data["."][0]['search_result'])?$this->_data["."][0]['search_result']:'').'
		</form>
	</div>';}$_tpl .= '
<!--<img src="template/images/new_record'.(isset($this->merge['ucp']['new'])?$this->merge['ucp']['new']:'').'.png" width="16" height="16" align="absmiddle" /> <a href="?mod='.(isset($this->_data["."][0]['module'])?$this->_data["."][0]['module']:'').'&amp;act=update&amp;type='.(isset($this->_data["."][0]['type'])?$this->_data["."][0]['type']:'').'&amp;do=new" title="New">New</a>
--><div class="l" >
		<a href="?mod='.(isset($this->_data["."][0]['module'])?$this->_data["."][0]['module']:'').'&amp;act=update&amp;parentid='.(isset($this->_data["."][0]['parentid'])?$this->_data["."][0]['parentid']:'').'&amp;type='.(isset($this->_data["."][0]['type'])?$this->_data["."][0]['type']:'').'&amp;do=new" title="" class="addNew btn">'.(isset($this->merge['button']['new_item'])?$this->merge['button']['new_item']:'').'</a>
		<!--style="background-image:url(../images/new_record'.(isset($this->merge['ucp']['new'])?$this->merge['ucp']['new']:'').'.png)" -->
	</div>
</div>
<!--<div class="breadcrumb_cat">'.(isset($this->_data["."][0]['xpath'])?$this->_data["."][0]['xpath']:'').'</div>
-->

<div class="pagination paging-top">
	<span class="r"><a href="./?mod='.(isset($this->_data["."][0]['module'])?$this->_data["."][0]['module']:'').'&amp;parentid='.(isset($this->_data["."][0]['parentid'])?$this->_data["."][0]['parentid']:'').'&type='.(isset($this->_data["."][0]['type'])?$this->_data["."][0]['type']:'').'&amp;page='.(isset($this->_data["."][0]['page'])?$this->_data["."][0]['page']:'').'">'.(isset($this->merge['lang']['sorted_default'])?$this->merge['lang']['sorted_default']:'').'</a></span>'.(isset($this->_data["."][0]['divpage'])?$this->_data["."][0]['divpage']:'').'
</div>

<div class="form">
<form id="form2" name="form2" method="post" action="" onSubmit="return checkSubmitAction(this)">
<table width="100%" border="0" cellspacing="0" cellpadding="2" class="table_list list table-Form1" id="table-list">
  <tr>
    <th width="3%" class="th-checkbox firstColumn"><input type="checkbox" name="checkall" '.(isset($this->_data["."][0]['display_checkall'])?$this->_data["."][0]['display_checkall']:'').' value="1" onClick="checkAll(\'#table-list\',this,\'pro\')" /></th>
    <th width="70%" class="th-name"><a href="./?mod='.(isset($this->_data["."][0]['module'])?$this->_data["."][0]['module']:'').'&amp;parentid='.(isset($this->_data["."][0]['parentid'])?$this->_data["."][0]['parentid']:'').'&type='.(isset($this->_data["."][0]['type'])?$this->_data["."][0]['type']:'').'&amp;page='.(isset($this->_data["."][0]['page'])?$this->_data["."][0]['page']:'').'&amp;by=name&amp;order='.(isset($this->_data["."][0]['switchorder'])?$this->_data["."][0]['switchorder']:'').'">'.(isset($this->merge['button']['header_name'])?$this->merge['button']['header_name']:'').'</a> '.(isset($this->merge['orderby']['name'])?$this->merge['orderby']['name']:'').'</th>
    <th width="5%" class="th-order"><a href="./?mod='.(isset($this->_data["."][0]['module'])?$this->_data["."][0]['module']:'').'&amp;parentid='.(isset($this->_data["."][0]['parentid'])?$this->_data["."][0]['parentid']:'').'&type='.(isset($this->_data["."][0]['type'])?$this->_data["."][0]['type']:'').'&amp;page='.(isset($this->_data["."][0]['page'])?$this->_data["."][0]['page']:'').'&amp;by=order_id&amp;order='.(isset($this->_data["."][0]['switchorder'])?$this->_data["."][0]['switchorder']:'').'">'.(isset($this->merge['button']['header_order'])?$this->merge['button']['header_order']:'').'</a> '.(isset($this->merge['orderby']['order_id'])?$this->merge['orderby']['order_id']:'').'</th>
    <th width="5%" class="th-status"><a href="./?mod='.(isset($this->_data["."][0]['module'])?$this->_data["."][0]['module']:'').'&amp;parentid='.(isset($this->_data["."][0]['parentid'])?$this->_data["."][0]['parentid']:'').'&type='.(isset($this->_data["."][0]['type'])?$this->_data["."][0]['type']:'').'&amp;page='.(isset($this->_data["."][0]['page'])?$this->_data["."][0]['page']:'').'&amp;by=active&amp;order='.(isset($this->_data["."][0]['switchorder'])?$this->_data["."][0]['switchorder']:'').'">'.(isset($this->merge['button']['header_status'])?$this->merge['button']['header_status']:'').'</a> '.(isset($this->merge['orderby']['active'])?$this->merge['orderby']['active']:'').'</th>
    <th width="18%" class="th-status lastColumn">'.(isset($this->merge['lang']['actions'])?$this->merge['lang']['actions']:'').'</th>
  </tr>
  <tbody class="pro">
  ';if(isset($this->_data['product.'])){for($i=0;$i< count($this->_data['product.']);$i++){$_tpl .= '
  <tr id="'.(isset($this->_data["product."][$i]["id"])?$this->_data["product."][$i]["id"]:'').'pro">
    <td class="th-checkbox firstColumn">
      <input type="checkbox" name="pro[]" value="'.(isset($this->_data["product."][$i]["id"])?$this->_data["product."][$i]["id"]:'').'" /></td>
    <td class="th-name">'.(isset($this->_data["product."][$i]["thumb_field"])?$this->_data["product."][$i]["thumb_field"]:'').''.(isset($this->_data["product."][$i]["list_field"])?$this->_data["product."][$i]["list_field"]:'').'</td>
    <td class="th-order"><span class="hide '.(isset($this->_data["."][0]['icon_updown'])?$this->_data["."][0]['icon_updown']:'').'"><a class="'.(isset($this->_data["product."][$i]["classup"])?$this->_data["product."][$i]["classup"]:'').'" href="?mod='.(isset($this->_data["."][0]['module'])?$this->_data["."][0]['module']:'').'&amp;act=orderbtn&amp;do=up&amp;id='.(isset($this->_data["product."][$i]["id"])?$this->_data["product."][$i]["id"]:'').'&amp;page='.(isset($this->_data["."][0]['page'])?$this->_data["."][0]['page']:'').'&amp;parentid='.(isset($this->_data["."][0]['parentid'])?$this->_data["."][0]['parentid']:'').'&amp;type='.(isset($this->_data["."][0]['type'])?$this->_data["."][0]['type']:'').'"><img src="template/images/icons_default/up.png" /></a> <a class="'.(isset($this->_data["product."][$i]["classdown"])?$this->_data["product."][$i]["classdown"]:'').'" href="?mod='.(isset($this->_data["."][0]['module'])?$this->_data["."][0]['module']:'').'&amp;act=orderbtn&amp;do=down&amp;id='.(isset($this->_data["product."][$i]["id"])?$this->_data["product."][$i]["id"]:'').'&amp;page='.(isset($this->_data["."][0]['page'])?$this->_data["."][0]['page']:'').'&amp;parentid='.(isset($this->_data["."][0]['parentid'])?$this->_data["."][0]['parentid']:'').'&amp;type='.(isset($this->_data["."][0]['type'])?$this->_data["."][0]['type']:'').'"><img src="template/images/icons_default/down.png" /></a></span><span class="order_id">'.(isset($this->_data["product."][$i]["order_id"])?$this->_data["product."][$i]["order_id"]:'').'</span></td>
    <td class="th-status"><a href="?mod='.(isset($this->_data["."][0]['module'])?$this->_data["."][0]['module']:'').'&amp;act=active&amp;id='.(isset($this->_data["product."][$i]["id"])?$this->_data["product."][$i]["id"]:'').'&amp;parentid='.(isset($this->_data["."][0]['parentid'])?$this->_data["."][0]['parentid']:'').'&amp;type='.(isset($this->_data["."][0]['type'])?$this->_data["."][0]['type']:'').'" title="'.(isset($this->merge['lang']['update_status'])?$this->merge['lang']['update_status']:'').'"><img src="template/images/icons_default/status'.(isset($this->_data["product."][$i]["active"])?$this->_data["product."][$i]["active"]:'').'.gif" /></a></td>
    <td class="th-status lastColumn"><a href="?mod='.(isset($this->_data["."][0]['module'])?$this->_data["."][0]['module']:'').'&amp;act=update&amp;id='.(isset($this->_data["product."][$i]["id"])?$this->_data["product."][$i]["id"]:'').'&amp;parentid='.(isset($this->_data["."][0]['parentid'])?$this->_data["."][0]['parentid']:'').'&amp;type='.(isset($this->_data["."][0]['type'])?$this->_data["."][0]['type']:'').'" title="'.(isset($this->merge['lang']['edit'])?$this->merge['lang']['edit']:'').'"><img src="template/images/icons_default/edit'.(isset($this->merge['ucp']['edit'])?$this->merge['ucp']['edit']:'').'.png" width="16" height="16" border="0" /></a> <a '.(isset($this->_data["product."][$i]["nodel"])?$this->_data["product."][$i]["nodel"]:'').' href="?mod='.(isset($this->_data["."][0]['module'])?$this->_data["."][0]['module']:'').'&amp;act=delete&amp;id='.(isset($this->_data["product."][$i]["id"])?$this->_data["product."][$i]["id"]:'').'&amp;parentid='.(isset($this->_data["."][0]['parentid'])?$this->_data["."][0]['parentid']:'').'&amp;type='.(isset($this->_data["."][0]['type'])?$this->_data["."][0]['type']:'').'" onClick="deleteConfirm(this); return false;" title="'.(isset($this->merge['lang']['delete'])?$this->merge['lang']['delete']:'').'"><img src="template/images/icons_default/delete'.(isset($this->merge['ucp']['delete'])?$this->merge['ucp']['delete']:'').'.png" width="16" height="16" /></a></td>
  </tr>
  ';}}$_tpl .= '
  </tbody>
</table>
		<div class="pagination paging-bottom">
			'.(isset($this->_data["."][0]['divpage'])?$this->_data["."][0]['divpage']:'').'
		</div>
<div class="bottom_callAction" style="'.(isset($this->_data["."][0]['display_checkall'])?$this->_data["."][0]['display_checkall']:'').'">			
			<strong>'.(isset($this->merge['button']['tools_copy'])?$this->merge['button']['tools_copy']:'').':</strong><br /> <select name="content_action">
    <option value="">'.(isset($this->merge['lang']['choose_action'])?$this->merge['lang']['choose_action']:'').'</option>
	<option value="delete">'.(isset($this->merge['button']['delete_item'])?$this->merge['button']['delete_item']:'').'</option>
	<option value="active">'.(isset($this->merge['button']['active_item'])?$this->merge['button']['active_item']:'').'</option>
	<option value="inactive">'.(isset($this->merge['button']['inactive_item'])?$this->merge['button']['inactive_item']:'').'</option>
  </select>
  <input name="cmd" type="submit" class="btn" id="cmd" value="'.(isset($this->merge['lang']['go'])?$this->merge['lang']['go']:'').'" />
</div>
</form></div>
'; if(isset($this->box['drapdrop_content'])){ $_tpl.= '	

<script type="text/javascript">
	var begin = null;
	$(\'#table-list tbody.pro\').tableDnD({
		onDragClass: "ondrag-list",
		onDragStart: function(table, row) {
			begin = $.tableDnD.serialize();
		},
		onDrop: function(table, row) {
			var after = $.tableDnD.serialize();
			if(begin != after){
				$.post(\'?mod='.(isset($this->_data["."][0]['module'])?$this->_data["."][0]['module']:'').'&act=order\', {\'data\':after,\'start\':'.(isset($this->_data["."][0]['start'])?$this->_data["."][0]['start']:'').'},function(data){
					var rows = after.replace(/\\[\\]=/ig,\'\').split(\'&\');
					for(var i in rows) $(\'tr#\'+rows[i]+\' td.th-order span.order_id\').html(parseInt(i) + parseInt('.(isset($this->_data["."][0]['start'])?$this->_data["."][0]['start']:'').'));

				})
			}
		}
    });
	
</script>
';}$_tpl .= '	


<!--end:body-->

				</div>			
			</div>
		</div>
		
		<div class="ft">
			&copy; Copyright '.(isset($this->_data["."][0]['system_year'])?$this->_data["."][0]['system_year']:'').' '.(isset($this->_data["."][0]['web_client'])?$this->_data["."][0]['web_client']:'').'.
		</div>
	</div>
</div>

<table width="5" height="100%" cellpadding="0" cellspacing="0" border="0" class="btn_expandMenu"><tr><td>&nbsp;</td></tr></table>


<!--start:master_footer-->
<div class="cms_overlay"></div>
<noscript>
	<style type="text/css">
		.wrapper{ display: none; }
	</style>
	<div class="noscript">JavaScript must be enabled in order for you to use '.(isset($this->_data["."][0]['web_client'])?$this->_data["."][0]['web_client']:'').' CMS. Please enable JavaScript by changing your browser options, then press <strong>F5</strong> to load page</div>
</noscript>

<!--end:master_footer-->


</body>
</html>'; ?>